name: "Tests"

on: [pull_request]
jobs:
  lint:
    name: Tests ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.3']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup Docker
      run: docker-compose up -d --build

    - name: Wait for Server to be ready
      run: sleep 10

    - name: Run FPM Tests
      run: docker compose exec fpm vendor/bin/phpunit --configuration phpunit.xml

    - name: Run Swoole Tests
      run: docker compose exec swoole vendor/bin/phpunit --configuration phpunit.xml